[package]
name = "sql-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
rig-core = "0.27.0"
reqwest = "0.12"
tokio = { version = "1.48.0", features = ["rt", "macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
