apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-agent
  labels:
    app: kube-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-agent
  template:
    metadata:
      labels:
        app: kube-agent
    spec:
      serviceAccountName: kube-agent
      containers:
        - name: kube-agent
          image: ccrawford4/ai-agent-api:v0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kube-agent-secrets
                  key: openai-api-key
            - name: CHAT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kube-agent-secrets
                  key: chat-api-key
            - name: PRODUCTION_MODE
              value: "true"
            - name: KUBE_API_SERVER
              value: "https://kubernetes.default.svc"
