apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-agent
  labels:
    app: kube-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-agent
  template:
    metadata:
      labels:
        app: kube-agent
    spec:
      serviceAccountName: kube-agent
      containers:
        - name: kube-agent
          image: ccrawford4/ai-agent-api:latest
          ports:
            - containerPort: 8080
