# The kube-agent service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-agent

# The role the kube-agent will use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]

# The ClusterRoleBinding to bind the role to the service account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-agent
subjects:
  - kind: ServiceAccount
    name: kube-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: kube-agent
  apiGroup: rbac.authorization.k8s.io
